db.host=sqlserver
db.port=1433
db.name=ZavaBankDB
db.user=sa
db.password=YourStrong!Passw0rd
currency.service.baseUrl=http://zava-currency-service:8080
ledger.service.baseUrl=http://zava-ledger:8080
ledger.settlement.accountId=1
rabbitmq.host=rabbitmq
rabbitmq.port=5672
rabbitmq.user=guest
rabbitmq.password=guest
rabbitmq.exchange=wire.events
rabbitmq.routing.key.prefix=wire
